name: an_toast
description: "A Flutter toast library with usage identical to Android would provide a simple API for displaying toast messages in Flutter."
version: 1.0.0
homepage: https://github.com/aymtools/an_toast
topics:
  - toast

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cancellable: ^2.3.1

dev_dependencies:
  flutter_lints: any

flutter:

